apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-web-sa
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: secret-reader
rules:
# Overly permissive - can read ALL secrets in namespace
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
# Can also list pods and services
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
# Can read configmaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-web-binding
  namespace: production
subjects:
- kind: ServiceAccount
  name: python-web-sa
  namespace: production
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
# Additional permissions to discover other namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-viewer
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: python-web-namespace-viewer
subjects:
- kind: ServiceAccount
  name: python-web-sa
  namespace: production
roleRef:
  kind: ClusterRole
  name: namespace-viewer
  apiGroup: rbac.authorization.k8s.io
